"""
Health timeline export for PulseCare.

generate_health_timeline() produces a structured document the caregiver
can bring to (or send ahead of) a physician appointment — saving intake
time and giving the doctor a longitudinal view they'd otherwise never have.
"""
from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone

import config
from tools.memory_tools import query_history


def generate_health_timeline(days: int = 30) -> str:
    """
    Generate a structured health timeline document.
    Returns markdown suitable for download and printing.
    """
    history = query_history(days=days)
    if not history:
        return "No health entries found for this period."

    now = datetime.now(timezone.utc)
    report_date = now.strftime("%B %d, %Y")
    dates = [e["date"] for e in history]
    date_start = min(dates)
    date_end = max(dates)

    all_symptoms: list[str] = []
    sleep_vals: list[float] = []
    sev_vals: list[int] = []
    for e in history:
        for s in e.get("symptoms", []):
            if s:
                all_symptoms.append(s.lower())
        if e.get("sleep_hours") is not None:
            sleep_vals.append(float(e["sleep_hours"]))
        if e.get("severity") is not None:
            sev_vals.append(int(e["severity"]))

    sym_counts = Counter(all_symptoms)
    top_syms = sym_counts.most_common(8)
    avg_sleep = round(sum(sleep_vals) / len(sleep_vals), 1) if sleep_vals else None
    avg_sev = round(sum(sev_vals) / len(sev_vals), 1) if sev_vals else None
    symp_days = len([e for e in history if e.get("symptoms")])

    poor_sleep = [e for e in history if e.get("sleep_hours") and float(e["sleep_hours"]) < 6.5]
    poor_sleep_syms = Counter(
        s.lower() for e in poor_sleep for s in e.get("symptoms", []) if s
    )

    sorted_history = sorted(history, key=lambda e: e["date"])

    lines = [
        f"# {config.APP_TITLE} — Patient Health Timeline",
        f"**Patient:** {config.PARENT_NAME}, age {config.PARENT_AGE}",
        f"**Report generated:** {report_date}",
        f"**Period:** {date_start} to {date_end} ({days} days)",
        f"**Entries:** {len(history)} check-ins",
        "",
        "---",
        "",
        "## Summary Statistics",
        "",
        f"- **Total symptom occurrences:** {len(all_symptoms)}",
        f"- **Days with symptoms:** {symp_days} of {len(history)}",
    ]
    if avg_sleep is not None:
        lines.append(f"- **Average sleep (logged nights):** {avg_sleep} hours")
    if avg_sev is not None:
        lines.append(f"- **Average symptom severity (1–10):** {avg_sev}")

    lines += ["", "---", "", "## Most Frequent Symptoms", ""]
    for sym, cnt in top_syms:
        lines.append(f"- **{sym.title()}** — {cnt} occurrence{'s' if cnt != 1 else ''}")

    if poor_sleep_syms:
        lines += [
            "", "---", "", "## Observed Correlations", "",
            "### Symptoms Correlated with Poor Sleep (<6.5 hrs)",
        ]
        for sym, cnt in poor_sleep_syms.most_common(5):
            lines.append(f"- {sym.title()}: {cnt} occurrence{'s' if cnt != 1 else ''} on low-sleep nights")

    lines += [
        "", "---", "", "## Chronological Log", "",
        "| Date | Symptoms | Sleep (hrs) | Severity | Notes |",
        "|------|----------|-------------|----------|-------|",
    ]
    for e in sorted_history:
        syms_str = ", ".join(e.get("symptoms", [])) or "—"
        slp = str(e["sleep_hours"]) if e.get("sleep_hours") is not None else "—"
        sev = str(e["severity"]) if e.get("severity") is not None else "—"
        note = (e.get("notes") or "").replace("|", "/").replace("\n", " ")[:80]
        lines.append(f"| {e['date']} | {syms_str} | {slp} | {sev} | {note} |")

    lines += [
        "", "---", "", "## Notes for the Physician", "",
        f"This report was generated by {config.APP_TITLE}, a family eldercare monitoring tool.",
        "All entries are patient-reported via voice check-in, structured automatically.",
        "This document is a patient-reported symptom journal, not a diagnostic tool.",
        "",
        f"*{config.APP_TITLE} is not a medical device and does not make diagnoses.*",
        "*Please use this as supplemental intake information.*",
    ]

    return "\n".join(lines)
